# Generated by Django 5.1.1 on 2024-11-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('mediaFormat', models.CharField(choices=[('VHS', 'VHS'), ('DVD', 'DVD'), ('BR', 'BluRay'), ('4K', '4K UHD')], max_length=100)),
            ],
        ),
    ]
